[tool.poetry]
name = "grobid"
version = "0.2.0"
description = "Python library for serializing GROBID TEI XML to dataclass"
authors = ["Omar Zeghouani <omarzeghouanii@gmail.com>"]
license = "MIT"
packages = [
    { include = "grobid", from = "src" }
]
include = [
    { path = "tests", format = "sdist" }
]

readme = "README.md"
repository = "https://github.com/ram02z/grobid"
keywords = ["GROBID", "XML", "dataclass"]

classifiers = [
  "License :: OSI Approved :: MIT License",
  "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = ">=3.11, <4.0"
lxml = "^5.3.2"
beautifulsoup4 = "^4.13.3"
httpx = "^0.28.1"
orjson = {optional = true, version = "^3.7.8"}

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
pytest = "^8.3.5"
pytest-asyncio = "^0.26.0"
respx = "^0.22.0"
isort = {extras = ["colors"], version = "^6.0.1"}
coverage = {extras = ["toml"], version = "^6.5.0"}
coveralls = "^3.3.1"
pydocstyle = "^6.1.1"
flake8 = "^7.2.0"
flake8-docstrings = "^1.7.0"
PyMuPDF = "^1.25.5"
Sphinx = "^5.0.2"
myst-parser = "^0.18.0"
furo = "^2022.6.21"

[tool.poetry.extras]
json = ["orjson"]

[tool.isort]
profile = "black"
extend_skip = ["docs"]

[tool.pydocstyle]
convention = "google"
match = "(?!__init).*\\.py"
match-dir = "^(?!(.venv|docs)).*"

[tool.black]
target-version = ["py310"]
extend-exclude = "docs"

[tool.coverage.run]
omit = ["*tests*"]

[tool.coverage.report]
exclude_lines = ["if __name__ == .__main__.:", "except ImportError:"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
